[package]
name = "rust-book-examples"
version = "0.1.0"
authors = ["Neil Kistner <neil.kistner@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.0"
